#!/bin/bash
# Title: artemisCollector
#
#
#   ________  ________  _________  _______   _____ ______   ___  ________
#  |\   __  \|\   __  \|\___   ___\\  ___ \ |\   _ \  _   \|\  \|\   ____\
#  \ \  \|\  \ \  \|\  \|___ \  \_\ \   __/|\ \  \\\__\ \  \ \  \ \  \___|_
#   \ \   __  \ \   _  _\   \ \  \ \ \  \_|/_\ \  \\|__| \  \ \  \ \_____  \
#    \ \  \ \  \ \  \\  \|   \ \  \ \ \  \_|\ \ \  \    \ \  \ \  \|____|\  \
#     \ \__\ \__\ \__\\ _\    \ \__\ \ \_______\ \__\    \ \__\ \__\____\_\  \
#      \|__|\|__|\|__|\|__|    \|__|  \|_______|\|__|     \|__|\|__|\_________\
#                                                                  \|_________|
#
#
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# Author: Andrew Withers (atw127@psu.edu, atw31337@gmail.com)

DIR=$(grep SDIR /etc/artemis.conf | cut -d'=' -f2)

exec 2> >(sed "s/^/$(date +'%b %e %Y %T'): /" >> /var/log/artemis.err)

# Got r00t?
if [[ $(id -u) -ne 0 ]]; then
        echo "Root privilege required. Try using sudo"
        exit 0
fi

# Create a tmpfs directory to track the worker PIDs
! [[ -d /opt/artemis/workers/ ]] && mkdir -p /opt/artemis/workers/
! mount | grep -q /opt/artemis/workers && mount -t tmpfs -o size=1m tmpfs /opt/artemis/workers/
chmod 600 /opt/artemis/workers/

# Start the artemisForwarder
/usr/bin/artemisForwarder & AFPID=$!

inotifywait -q -m -e create,moved_to --format '%w%f' "$DIR" | while read FILE
do
	TSTAMP="$(date +%Y-%m-%d) $(date +%T)"
	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO Queue (DateTime, FileName) VALUES ('$TSTAMP', '$FILE');"
done

# Send a stop signal to the forwarder process and wait for it to shutdown
kill -1 $AFPID
wait $AFPID

# Remove the the tmpfs directory
mount | grep -q /opt/artemis/workers && umount /opt/artemis/workers/
[[ -d /opt/artemis/workers/ ]] && rm -rf /opt/artemis/workers/

exit
