#!/bin/bash
# Title: artemisInit
# Version: 1.00.00
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Author: Andrew Withers (atw127@psu.edu, atw31337@gmail.com)

case "$1" in
start)
        /usr/bin/artemis & 2>>/var/log/artemis.err
        ;;
stop)
        pkill -1 "inotify"
	while [[ -n $(pgrep -x artemis) ]]; do
		sleep 0.1
	done
	;;
restart)
        $0 stop
        $0 start
        ;;
esac

exit $?
