#!/bin/bash
# Title: artemis-brolog-cleanup
# Description: Maintains the size of the Artemis log files in /var/log/
# Version 1.00.00
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Author: Andrew Withers (atw127@psu.edu, atw31337@gmail.com)


# Ensure that all archived log files are currently zipped
gzip /opt/artemis/logs/artemis-files.log.* > /dev/null 2>&1

# If the archived files have reached their maximum number of 6 archives then delete the oldest one
if [[ -e /opt/artemis/logs/artemis-files.log.6.gz ]]; then
	rm -f /opt/artemis/logs/artemis-files.log.6.gz
fi
for (( i=5; i>0; i-- )); do	# Determine the number of the oldest archived file
	if [[ -e /opt/artemis/logs/artemis-files.log.$i.gz ]]; then
        	for (( x=$i; x>0; x-- )); do	# When the number of the oldest archived file is found begin rotating
			mv /opt/artemis/logs/artemis-files.log.$x.gz /opt/artemis/logs/artemis-files.log.$(((x+1))).gz
		done
		break
	fi
done
# Move the current log file to the first archived position
mv /opt/artemis/logs/artemis-files.log /opt/artemis/logs/artemis-files.log.1
# Remove entries in the log for files that were not extracted by Bro in order to minimize log file storage size
sed -i '/extracted/!d' /opt/artemis/logs/artemis-files.log.1
# Zip the most recent archived log
gzip /opt/artemis/logs/artemis-files.log.1
exit
