#!/bin/bash
# Title: artemis
# Version: 1.00.00
#
#
#   ________  ________  _________  _______   _____ ______   ___  ________
#  |\   __  \|\   __  \|\___   ___\\  ___ \ |\   _ \  _   \|\  \|\   ____\
#  \ \  \|\  \ \  \|\  \|___ \  \_\ \   __/|\ \  \\\__\ \  \ \  \ \  \___|_
#   \ \   __  \ \   _  _\   \ \  \ \ \  \_|/_\ \  \\|__| \  \ \  \ \_____  \
#    \ \  \ \  \ \  \\  \|   \ \  \ \ \  \_|\ \ \  \    \ \  \ \  \|____|\  \
#     \ \__\ \__\ \__\\ _\    \ \__\ \ \_______\ \__\    \ \__\ \__\____\_\  \
#      \|__|\|__|\|__|\|__|    \|__|  \|_______|\|__|     \|__|\|__|\_________\
#                                                                  \|_________|
#
#
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#
# Author: Andrew Withers (atw127@psu.edu, atw31337@gmail.com)

CONF=/etc/artemis.conf

source /opt/artemis/parsOpts.sh

usage() {
cat <<EOF

Artemis Network Traffic Virus Monitor
Usage: artemis [OPTION]

	Options:

		-h	   		This message
		-v			Print version information
		-f	    		Flush the hash cache
		-w <SHA256 Hash>	Add a SHA256 hash to the whitelist
		-b <SHA256 Hash>	Add a SHA256 hash to the blacklist

EOF
}

LogsEntry() {
SIZE=$(du -b "$1" | awk '{print $1}')
# If the filename contains a . then set the last extension as the filetype; otherwise make the filetype blank
if echo "$3" | grep -q "\."; then
	FILETYPE=$(echo "$3" | rev | cut -d'.' -f1 | rev)
	if [[ ${#FILETYPE} -gt 5 ]]; then
		FILETYPE=$(echo "$FILETYPE" | head -c5)
	fi
else
	FILETYPE=""
fi
LOGSID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO Logs (DateTime, Hash, FileName, FileSize, FileType) \
VALUES ('$(date +%Y-%m-%d) $(date +%T)', '$2', '$3', $SIZE, '$FILETYPE'); SELECT LAST_INSERT_ID();")
}

sendAlert() {
TFILE=$(mktemp -p /tmp/artemis/)	# Temporary file for alert email output
printf "From: %s\nTo: %s\nSubject: Malware Detected!\n\n" "$HOSTNAME" "$EMAIL"  > "$TFILE"
printf "%s: %s has detected malware on the network.\n " "$TSTAMP" "$HOSTNAME" >> "$TFILE"
printf "SHA256: %s\n" "$HASH" >> "$TFILE"
if [[ -n $IDIR ]]; then
	 printf "A copy of the infected file(s) can be located in %s\n" "$IDIR" >> "$TFILE"
fi
mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT FileName, Source, CONCAT('->') AS Arrow, Destination FROM Logs WHERE EntryID=$LOGSID;" >> "$TFILE"
if [[ -e /opt/artemis/cache/$HASH ]]; then
	mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT FileName, Source, CONCAT('->') AS Arrow, Destination FROM Logs WHERE EntryID IN ($IDLIST);" >> "$TFILE"
fi
sendmail -vt < "$TFILE"
rm -f "$TFILE"
}

file_integrity_chk() {         # checks and, if necessary, waits for a file to finish being written to disk
local hash
while [[ $(sha256sum "$1" | cut -d' ' -f1) != "$hash" ]]; do
        hash=$(sha256sum "$1" | cut -d' ' -f1)
        sleep 0.1
done
}

getSrcDst() {
# Check the current log
if [[ -e /opt/artemis/logs/artemis-files.log ]]; then
        SOURCE=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$2}' | sed 's/"//g')
        DEST=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$4}' | sed 's/"//g')
fi

# If the Source/Destination are not located there, check the most recently archived log file
if [[ -z $SOURCE ]] || [[ -z $DEST ]] && [[ -f /opt/artemis/logs/artemis-files.log.1.gz ]]; then
        TEMPID=$(date +%s%N)
        file_integrity_chk /opt/artemis/logs/artemis-files.log.1.gz # Ensure that the file has been completely written to disk during log rotation before proceeding
        cp /opt/artemis/logs/artemis-files.log.1.gz /tmp/artemis/"$TEMPID".temp.gz
        gzip -d /tmp/artemis/"$TEMPID".temp.gz
        SOURCE=$(grep "$FILENAME" /tmp/artemis/"$TEMPID".temp | head -n1 | awk -F'[][]' '{print$2}' | sed 's/"//g')
        DEST=$(grep "$FILENAME" /tmp/artemis/"$TEMPID".temp | head -n1 | awk -F'[][]' '{print$4}' | sed 's/"//g')
        rm /tmp/artemis/"$TEMPID".temp
fi

# If the Source/Destination are not located in the archived log either, then wait for the data to be written to the current log
if [[ -z $SOURCE ]] || [[ -z $DEST ]]; then
        for (( i=0; i < 300; i++ )); do # For loop prevents infinite loops caused by log rotation
                local counter=0
		while ! [[ -e /opt/artemis/logs/artemis-files.log ]]; do       # Prevents missing file errors during log rotation
                                sleep 0.1
				((counter++))
				if [[ $counter -ge 300 ]]; then	# Prevents an inifinite while loop
					break 2
				fi
                done
                SOURCE=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$2}' | sed 's/"//g')
                DEST=$(grep "$FILENAME" /opt/artemis/logs/artemis-files.log | head -n1 | awk -F'[][]' '{print$4}' | sed 's/"//g')
                if [[ -z $SOURCE ]] || [[ -z $DEST ]]; then
                        sleep 1
                else
                        break
                fi
        done
fi
}


prescan() {
if [[ -e $1 ]] && [[ -s $1 ]]; then    # Check that file length is nonzero
	TSTAMP="$(date +%Y-%m-%d) $(date +%T)"
	file_integrity_chk "$1"
	HASH=$(sha256sum "$1" | awk '{ print $1 }')
	FILENAME=$(basename "$1")      # File name only
	LogsEntry "$1" "$HASH" "$FILENAME"
	HASHID=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT HashID FROM Cache WHERE Hash='$HASH' LIMIT 1;")
	if grep -qw "$HASH" "$LISTLOC"/blacklist; then	# Compare the hash against the blacklist
		getSrcDst
		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=4, Source='$SOURCE', Desintation='$DEST' WHERE EntryID=$LOGSID;"
		if [[ -n $IDIR ]]; then
                	mv "$DIR$FILENAME" "$IDIR$FILENAME"
                	chmod 600 "$IDIR$FILENAME"
		fi
		sendAlert
	elif grep -qw "$HASH" "$LISTLOC"/whitelist; then   # Compare the hash against the whitelist
                getSrcDst
                mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=0, Queued=0, Result=3, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
	elif [[ -z $HASHID ]]; then	# Hash does not exist in the Cache Table
		QUEUED=1
		ENTRYTIME="$(date +%s).$(date +%N | head -c3)"
		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "INSERT INTO Queue (FileName, TimeStamp, LogsID, EntryTime) VALUES ('$1', '$TSTAMP', $LOGSID, $ENTRYTIME);"
		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Queued=$QUEUED WHERE EntryID=$LOGSID;"
	else	# Hash is present in the Cache table
		SCANNED=0
		QUEUED=0
		getSrcDst
		RESULT=$(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT Result FROM Cache WHERE HashID=$HASHID;")
		# Update the Logs and Cache table entries
		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Scanned=$SCANNED, Queued=$QUEUED, Source='$SOURCE', Destination='$DEST' WHERE EntryID=$LOGSID;"
		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Cache SET Hits=Hits+1, TimeStamp=$(date +%s%N) WHERE HashID=$HASHID;"
		if [[ $RESULT == "NULL" ]]; then
			echo "$LOGSID" >> /opt/artemis/cache/"$HASH"
		else	# Result is present in the Cache table

			# Update the result in the Logs table
                        mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "UPDATE Logs SET Result=$RESULT WHERE EntryID=$LOGSID;"
			if [[ $RESULT -eq 1 ]]; then
				if [[ -n $IDIR ]]; then
					mv "$DIR$FILENAME" "$IDIR$FILENAME"
					chmod 600 "$IDIR$FILENAME"
				fi
				sendAlert
			fi
		fi
	fi
fi
}

exec 2> /var/log/artemis.err

# Got r00t?
if [[ $(id -u) -ne 0 ]]; then
	echo "Root privilege required. Try using sudo"
	exit 0
fi

# Check that the configuration file exists
if [[ ! -f $CONF ]]; then
	echo Artemis: Configuration file does nost exist!
	exit 1
fi

# Parse options
while [[ $OPTIND -lt $# ]];do
	parsOpts "$@" "h,help,v,f,w:,b:"
	case $OPT in
	h|help)
		usage
		exit 0
		;;
	v)
		echo "Artemis Network Traffic Virus Monitor v$(grep VERSION /etc/artemis.conf | cut -d'=' -f2)"
		exit 0
		;;
	f)
		mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Cache;" > /dev/null
		echo "Artemis: Cache has been flushed"
		exit 0
		;;
	w)
		echo "$OPTARG" >> /opt/artemis/whitelist
		if [[ -e /opt/artemis/cache/whitelist ]]; then
			echo "$OPTARG" >> /opt/artemis/cache/whitelist
		fi
		exit 0
		;;
	b)
		echo "$OPTARG" >> /opt/artemis/blacklist
		if [[ -e /opt/artemis/cache/blacklist ]]; then
			echo "$OPTARG" >> /opt/artemis/cache/blacklist
		fi
		exit 0
		;;
	?)
		usage
		exit 1
		;;
	:)
		echo "Invalid number of arguments for option $OPTARG. $OPTARG requires $NUMARGS argument(s)."
		exit 1
		;;
	esac
done
shift "$OPTIND"

# Get variables from artemis.conf
EMAIL=$(grep EMAIL "$CONF" | cut -d'=' -f2)
DIR=$(grep SDIR "$CONF" | cut -d'=' -f2)
IDIR=$(grep IDIR "$CONF" | cut -d'=' -f2)
MAXPROC=$(grep MAXPROC "$CONF" | cut -d'=' -f2)
MAXHASH=$(grep MAXHASH "$CONF" | cut -d'=' -f2)

# Check that all variables contain values
if [[ -z "$DIR" ]] || [[ -z "$MAXPROC" ]] || [[ -z "$MAXHASH" ]] || [[ -z "$EMAIL" ]]; then
	echo Artemis: Invalid configuration detected! Check that the conf file has been properly configured.
	exit 1
fi

# Create the infected file directory if it does not exist
if [[ -n $IDIR ]]; then
	if ! [[ -d $IDIR ]]; then
		mkdir -pm 600 "$IDIR"
	fi
fi

# Create a temporary file directory if it does not exist
if ! [[ -d /tmp/artemis/ ]]; then
	mkdir -m 660 /tmp/artemis/
fi

# Mount the cache directory
if ! [[ -d /opt/artemis/cache/ ]]; then
	mkdir -p /opt/artemis/cache/
fi
if  ! mount | grep -q /opt/artemis/cache ; then
	mount -t tmpfs -o size=2m tmpfs /opt/artemis/cache/
	chmod 600 /opt/artemis/cache/
fi

# Create a woker pid directory in the cache
mkdir /opt/artemis/cache/workers/

# Load the whitelist and blacklist into memory if space permits
if cp /opt/artemis/whitelist /opt/artemis/cache/ && cp /opt/artemis/blacklist /opt/artemis/cache/; then
	chmod 600 /opt/artemis/cache/whitelist /opt/artemis/cache/blacklist
	LISTLOC="/opt/artemis/cache"
else
	rm /opt/artemis/cache/*list
	LISTLOC="/opt/artemis"
fi

# Start the Orion scanner
/usr/bin/orion &

inotifywait -q -m -e create,moved_to --format '%w%f' "$DIR" | while read FILE
do
	prescan "$FILE" &
done

# Shutdown
pkill -9 orion
pkill -9 clamscan

# Cleanup
umount /opt/artemis/cache/
rm -rf /opt/artemis/cache/
mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Logs WHERE Result IS NULL;"
mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "DELETE FROM Cache WHERE Result IS NULL;"
if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM Queue;") -ne 0 ]]; then
        read -p 'Some files are still queued to be scanned. Would you like to remove these files from the queue before stopping? [y/N]: ' ANSWER && ANSWER=${ANSWER,,}
        if [[ $ANSWER == 'y' ]]; then
                mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -e "TRUNCATE TABLE Queue;"
        fi
fi
if [[ -d /tmp/artemis/ ]]; then
	rm -rf /tmp/artemis/
fi

pkill -x -9 artemis
exit
