#!/bin/bash
# Title: artemis-logfile-cleanup
# Description: Maintains the size of the Artemis log files in /var/log/
# Version 1.00.00
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Author: Andrew Withers (atw127@psu.edu, atw31337@gmail.com)

exec 2> >(sed "s/^/$(date +'%b %e %Y %T'): /" >> /var/log/artemis.err)

MAXSIZE=5000000 # in bytes

SIZE=$(stat -c%s /var/log/virus-scan.log)


if [[ $SIZE -gt $MAXSIZE ]]; then
	# Ensure that all log file archives are currently zipped
	gzip /var/log/virus-scan.log.* > /dev/null 2>&1
	# If the archived files have reached their maximum number of 6 archives then delete the oldest one
	if [[ -e /var/log/virus-scan.log.6.gz ]]; then
		rm -f /var/log/virus-scan.log.6.gz
	fi
	for (( i=5; i>0; i-- )); do	# Determine the number of the oldest archived file
		if [[ -e /var/log/virus-scan.log.$i.gz ]]; then
			for (( x=$i; x>0; x-- )); do	# When the number of the oldest archived file is found begin rotating
				mv /var/log/virus-scan.log.$x.gz /var/log/virus-scan.log.$(((x+1))).gz
			done
			break
		fi
	done
	# Move the current log file to the first archived position and zip it
	mv /var/log/virus-scan.log /var/log/virus-scan.log.1
	gzip /var/log/virus-scan.log.1
fi
