#!/bin/bash
# Title: hashdb_load
# Description: Loads a list of hashes from a txt file into the Artemis database as either a whitelist or a blacklist
# Author: Andrew T. Withers (atw31337@gmail.com)

. /opt/artemis/parsOpts.sh

usage() {
cat <<EOF

hashdb_load - Artemis whitelist/blacklist database loader
Usage: hashdb_load [OPTION] <file path>

	Options:
		-w <file path>		Add the file contents to the whitelist
		-b <file path>		Add the file contents to the blacklist

EOF
}

# Got r00t?
if [[ $(id -u) -ne 0 ]]; then
        echo "Root privilege required. Try using sudo"
        exit 0
fi

# Parse options
while [[ $OPTIND -lt $# ]]; do
	parsOpts "$@" "w:,b:"
	case $OPT in
		h|help)
			usage
			exit 0
			;;
		w)
			LIST="Whitelist"
			FILE="$OPTARG"
			;;
		b)
			LIST="Blacklist"
			FILE="$OPTARG"
			;;
		\?)
			usage
			exit 1
			;;
		:)
			echo "Invalid number of arguments for option $OPTARG. $OPTARG requires $NUMARGS argument(s)."
			exit 1
			;;
	esac
done

if [[ -z $LIST ]] || [[ -z $FILE ]]; then
	usage
	exit 1
fi

# Copy the original file to a temporary file and remove comments
TEMP=$(mktemp)
cp "$FILE" "$TEMP"
sed -i '/#/d' "$TEMP"

# Add each line to the appropriate field in the appropriate table
while read LINE; do
	if [[ $(echo -n $LINE | wc -c) -eq 32 ]]; then		# MD5
		if [[ $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM $LIST WHERE MD5='$LINE';") -eq 0 ]]; then
			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO $LIST (MD5) VALUES ('$LINE');"
		fi
	elif [[ $(echo -n $LINE | wc -c) -eq 64 ]]; then	# SHA256
		if [[  $(mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "SELECT COUNT(*) FROM $LIST WHERE SHA256='$LINE';") -eq 0 ]]; then
			mysql --defaults-file=/etc/mysql/debian.cnf -D artemis -BN -e "INSERT INTO $LIST (SHA256) VALUES ('$LINE');"
		fi
	fi
done < "$TEMP"

# Remove the temporary file
rm "$TEMP"

exit 0
